### ISSUE TITLE
Add additional types

### ISSUE THREAD

**Issue by aleksandrenko** [stylesuxx/graphql-custom-types#2]
Hello,
It's great to provide the community with additional types for GraphQL but I see that some are missing:

1. LimitedInt
2. LimitedFloat
3. LatLng

With this the collection will become complete.

**Comment by stylesuxx** [comment]
By limited int and float you mean a range, I guess?

So, do you want to contribute? PR's are welcome ;-)

**Comment by aleksandrenko** [comment]
Yea, you can think about it like a range. 
I thought about making a PR but I have something else I'm trying to figure out. If I do all I need and come to the point I need those types I will contribute them :)

If you have good knowledge about designing graphql schemas and have a couple of minutes I can ask you about one think i can not find online?

**Comment by stylesuxx** [comment]
Sure you can ask your question, but I am not sure if I can really help you, maybe some graphql related slack channel would be better ;-)

**Comment by aleksandrenko** [comment]
var personType = new graphql.GraphQLObjectType({
  name: 'personType',
  fields: function() { return {
    id: { type: graphql.GraphQLString },
    name: { type: graphql.GraphQLString },
    friends: { type: graphql.GraphQLList(personType) }
  }})
});

I want to add additional information about each friend. Let's say ... "friends_since". But i don't see a possibility for this. Do you have a suggestion or place where can I ask and got an answer? :)

**Comment by stylesuxx** [comment]
Well, I would do it like so:
* friends is a list of friendsType.
* friendsType has a field with personType and a since field

**Comment by stylesuxx** [comment]
Closing this down. PR's are still welcome if somebody needs, and is willing to implement those types.
