### ISSUE TITLE
GraphQLPassword typescript error

### ISSUE THREAD

**Issue by darkadept** [stylesuxx/graphql-custom-types#26]
In your `index.d.ts` file the definition for `GraphQLPassword` is this:

```js
 class GraphQLPassword extends GraphQLCustomScalarType {
    constructor(min?: number, max?: number, alphabet?: boolean, complexity?: {
      alphaNumeric?: boolean,
      mixedCase?: boolean,
      specialChars?: boolean,
    });
  }
```

The `alphabet` parameter is marked as `boolean`. Isn't this supposed to be a string?

**Comment by stylesuxx** [comment]
Yes, you are right. PR's are welcome.

Mike Kornelson <notifications@github.com> schrieb am Mo., 1. Apr. 2019,
23:13:

**Comment by arjunyel** [comment]
Fix: https://github.com/stylesuxx/graphql-custom-types/pull/27
