### ISSUE TITLE
1.1.1970 midnight validates as invalid

### ISSUE THREAD

**Issue by jurcovicova** [stylesuxx/graphql-custom-types#5]
Following query:
````
{
  myQuery(date: "1970-01-01T00:00:00.000Z")
}
````

returns:
````
Query error: String is not a valid date time string
````
-----------------------
However, a year later 1.1.1971 midnight works:
````
{
  myQuery(date: "1971-01-01T00:00:00.000Z")
}
````

Other working dates:
- `1970-01-01T00:00:00.001Z` - 1ms after 1.1.1970 midnight
- `1969-12-31T23:59:59.999Z` - 1ms before 1.1.1970 midnight

-----------------------
The reason is that `Date.parse('1970-01-01T00:00:00.000Z')` returns 0 and [this condition](https://github.com/stylesuxx/graphql-custom-types/blob/eaba430f5ee033ed03fd368a80c89a28a688841b/src/scalars.js#L131) then evaluates to false.

**Comment by Glavin001** [comment]
You could change:

```javascript
if(!Date.parse(ast.value)) {
      throw new GraphQLError('Query error: String is not a valid date time string', [ast]);
    }
```

to

```javascript
if(isNaN(Date.parse(ast.value))) {
      throw new GraphQLError('Query error: String is not a valid date time string', [ast]);
    }
```

References:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
- http://stackoverflow.com/questions/1353684/detecting-an-invalid-date-date-instance-in-javascript

**Comment by Glavin001** [comment]
https://github.com/stylesuxx/graphql-custom-types/pull/6 fixes your issues and has tests to confirm.

**Comment by jurcovicova** [comment]
@Glavin001 Thank you.
