### ISSUE TITLE
field type must be Output Type but got: Email

### ISSUE THREAD

**Issue by Glavin001** [stylesuxx/graphql-custom-types#7]
```
[ 'Error: UserEmail.address field type must be Output Type but got: Email.',
```

The error comes from https://github.com/graphql/graphql-js/blob/39744381d5173795d3b245dcb5d86e78bb3638fe/src/type/definition.js#L408-L410
Which comes from `namedType instanceof GraphQLScalarType` returning `false` in https://github.com/graphql/graphql-js/blob/39744381d5173795d3b245dcb5d86e78bb3638fe/src/type/definition.js#L95-L104

The issue as it pertains to this package is that graphql-custom-types has its own copy of dependency GraphQL. Thus, `namedType instanceof GraphQLScalarType` is checking the overall project's `GraphQLScalarType` versus graphql-custom-types' `GraphQLScalarType` instance.

Changing `dependencies` to `peerDependencies` in `package.json` resolves this issue and I have tested locally.

**Comment by stylesuxx** [comment]
Makes sense. Thank you for contributing.
I merged this into a seperate branch and adapted the travis config to install the peer dependencies before travis runs *npm install*. On newer npm versions peer dependencies are no longer installed automatically.

**Comment by Glavin001** [comment]
Would you be able to publish v6.0.0 to npm? I need this update for today, else my tests are failing :wink:. Thank you!

In the meantime I will make temporary changes under `node_modules`.

**Comment by stylesuxx** [comment]
Published it now.

**Comment by Glavin001** [comment]
Thank you!
